const kinLevelTasks={medium:new Set(['offset','convert-speed','braking','graph-total','graph-brake','from-rest-distance','stop-distance','fall-total-time','boat-resultant','horizontal-launch','drag-reason','circle-omega','circle-acceleration']),advanced:new Set(['negative-a','signed-area','reverse-distance','top-time','top-a','dot-product','cross-product','projectile-range','circle-force','circle-release'])};
const originalKinTask=kinTask;kinTask=function(id,...args){const level=id.startsWith('level-medium-')||kinLevelTasks.medium.has(id)?'medium':id.startsWith('level-advanced-')||kinLevelTasks.advanced.has(id)?'advanced':'easy';return kinState.level===level?originalKinTask(id,...args):''};
kinExtra=function(level,title,body){return kinState.level===level?`<section class="activity"><span class="badge">${level==='advanced'?KT('ADVANCED · OPTIONAL','LANJUTAN · OPSIONAL'):KT('MEDIUM','MENENGAH')}</span><h3>${title}</h3>${body}</section>`:''};
const kinGoals=[
[['Tell distance and displacement apart.','Bedakan jarak dan perpindahan.'],['Calculate displacement from signed positions.','Hitung perpindahan dari posisi bertanda.'],['Reconstruct a multi-stage journey from incomplete information.','Susun kembali perjalanan bertahap dari informasi yang belum lengkap.']],
[['Use distance or displacement to find an average.','Gunakan jarak atau perpindahan untuk mencari nilai rata-rata.'],['Convert speeds and keep units consistent.','Konversikan kelajuan dan gunakan satuan konsisten.'],['Find averages when different parts of a journey take different times.','Tentukan rata-rata ketika tiap bagian perjalanan memerlukan waktu berbeda.']],
[['Recognise zero and positive acceleration.','Kenali percepatan nol dan positif.'],['Calculate braking acceleration with the correct sign.','Hitung percepatan pengereman dengan tanda yang benar.'],['Explain speeding up after a reversal of direction.','Jelaskan pertambahan kelajuan setelah arah berbalik.']],
[['Read velocity and a rectangular area from a graph.','Baca kecepatan dan luas persegi panjang dari grafik.'],['Combine areas and calculate a negative slope.','Gabungkan luas dan hitung kemiringan negatif.'],['Separate signed displacement from total distance.','Pisahkan perpindahan bertanda dari jarak total.']],
[['Use a supplied equation for one calculation.','Gunakan persamaan yang tersedia untuk satu perhitungan.'],['Choose a constant-acceleration equation and solve it.','Pilih persamaan percepatan tetap lalu selesaikan.'],['Locate a turning point before calculating total distance.','Tentukan titik balik sebelum menghitung jarak total.']],
[['Calculate the velocity and distance of a dropped ball.','Hitung kecepatan dan jarak jatuh bola.'],['Work backward from drop height to fall time.','Tentukan waktu jatuh dari ketinggian.'],['Use upward-positive signs at the top of a vertical throw.','Gunakan tanda positif ke atas pada puncak lemparan vertikal.']],
[['Recognise components and perpendicular displacement.','Kenali komponen dan perpindahan saling tegak lurus.'],['Combine a boat’s velocity with a water current.','Gabungkan kecepatan perahu dengan arus air.'],['Distinguish scalar and vector products.','Bedakan perkalian skalar dan vektor.']],
[['Identify horizontal acceleration and velocity at the apex.','Kenali percepatan horizontal dan kecepatan di puncak.'],['Use vertical fall time to predict horizontal range.','Gunakan waktu jatuh vertikal untuk menentukan jangkauan horizontal.'],['Apply a range formula and check its assumptions.','Terapkan rumus jangkauan dan periksa asumsinya.']],
[['Recognise balanced forces at terminal velocity.','Kenali gaya seimbang pada kecepatan terminal.'],['Explain how increased drag changes terminal speed.','Jelaskan pengaruh pertambahan hambatan terhadap kelajuan terminal.'],['Use the linear-drag model to calculate acceleration.','Gunakan model hambatan linear untuk menghitung percepatan.']],
[['Explain why changing direction means acceleration.','Jelaskan mengapa perubahan arah berarti percepatan.'],['Calculate angular speed and centripetal acceleration.','Hitung kelajuan sudut dan percepatan sentripetal.'],['Find the inward resultant force and predict release motion.','Tentukan resultan gaya ke pusat dan prediksi gerak setelah dilepas.']],
[['Recall the essential ideas in 14 short questions.','Ingat kembali konsep inti melalui 14 soal singkat.'],['Apply the chapter concepts in 8 calculation questions.','Terapkan konsep bab dalam 8 soal perhitungan.'],['Solve 8 multi-step and reasoning problems.','Selesaikan 8 soal bertahap dan penalaran.']]
];
function kinSpecificTasks(section){if(kinState.level==='advanced'&&section===0)return `<section class="activity">${kinTask('level-advanced-path',KT('A walker starts at x = −2 m, walks 7 m right and then turns left. Total distance is 12 m. Find final position.','Pejalan mulai di x = −2 m, berjalan 7 m ke kanan lalu berbalik ke kiri. Jarak total 12 m. Tentukan posisi akhir.'),0,'m',KT('The leftward part is 12 − 7 = 5 m. Final position = −2 + 7 − 5 = <strong>0 m</strong>. Displacement is +2 m.','Bagian ke kiri = 12 − 7 = 5 m. Posisi akhir = −2 + 7 − 5 = <strong>0 m</strong>. Perpindahan = +2 m.'))}${kinTask('level-advanced-path-reason',KT('Can two journeys have the same displacement but different distances? Give an example.','Bisakah dua perjalanan memiliki perpindahan sama tetapi jarak berbeda? Berikan contoh.'),null,'',KT('Yes. Moving 4 m right has displacement +4 m and distance 4 m. Moving 6 m right then 2 m left has the same displacement but distance 8 m.','Ya. Bergerak 4 m ke kanan memberikan perpindahan +4 m dan jarak 4 m. Bergerak 6 m ke kanan lalu 2 m ke kiri memberikan perpindahan sama tetapi jarak 8 m.'))}</section>`;
if(kinState.level==='advanced'&&section===1)return `<section class="activity">${kinTask('level-advanced-average',KT('Travel 60 m at 3 m/s, then another 60 m in the same direction at 6 m/s. Find average speed for the whole trip.','Menempuh 60 m dengan 3 m/s, lalu 60 m lagi searah dengan 6 m/s. Tentukan kelajuan rata-rata seluruh perjalanan.'),4,'m/s',KT('Times: 60/3 = 20 s and 60/6 = 10 s. Average speed = 120/30 = <strong>4 m/s</strong>, not the arithmetic mean 4.5 m/s.','Waktu: 60/3 = 20 s dan 60/6 = 10 s. Kelajuan rata-rata = 120/30 = <strong>4 m/s</strong>, bukan rata-rata aritmetika 4.5 m/s.'))}${kinTask('level-advanced-return-v',KT('Now travel 60 m east at 3 m/s and return 60 m west at 6 m/s. Find average velocity.','Sekarang menempuh 60 m ke timur dengan 3 m/s lalu kembali 60 m ke barat dengan 6 m/s. Tentukan kecepatan rata-rata.'),0,'m/s',KT('The total time is 30 s, but displacement is zero. Average velocity = <strong>0 m/s</strong>; average speed is 4 m/s.','Waktu total 30 s, tetapi perpindahan nol. Kecepatan rata-rata = <strong>0 m/s</strong>; kelajuan rata-rata 4 m/s.'))}</section>`;
if(kinState.level==='advanced'&&section===8)return `<section class="activity">${kinTask('level-advanced-drag-a',KT('For a 1 kg falling object, g = 10 m/s² and drag F = bv with b = 0.5 kg/s. Find acceleration when downward velocity is 12 m/s. Downward is positive.','Untuk benda jatuh 1 kg, g = 10 m/s² dan hambatan F = bv dengan b = 0.5 kg/s. Tentukan percepatan saat kecepatan ke bawah 12 m/s. Ke bawah positif.'),4,'m/s²','Fdrag = 0.5 × 12 = 6 N. Fnet = 10 − 6 = 4 N. a = 4/1 = <strong>+4 m/s²</strong>.')}${kinTask('level-advanced-terminal',KT('For that object, find terminal velocity.','Untuk benda tersebut, tentukan kecepatan terminal.'),20,'m/s','vₜ = mg/b = (1 × 10)/0.5 = <strong>20 m/s</strong>.')}</section>`;return''}
const mediumChallenge=[
[['A car changes velocity from +15 to +3 m/s in 4 s. Find average acceleration.','Mobil berubah kecepatan dari +15 menjadi +3 m/s dalam 4 s. Tentukan percepatan rata-rata.'],-3,'m/s²','(3 − 15)/4 = <strong>−3 m/s²</strong>.'],
[['Start from rest and accelerate at +3 m/s² for 4 s. Find displacement.','Mulai dari diam dengan percepatan +3 m/s² selama 4 s. Tentukan perpindahan.'],24,'m','s = ½ × 3 × 4² = <strong>24 m</strong>.'],
[['Velocity increases linearly from 0 to 8 m/s in 3 s. Find displacement from the graph area.','Kecepatan bertambah linear dari 0 menjadi 8 m/s dalam 3 s. Tentukan perpindahan dari luas grafik.'],12,'m','s = ½ × 3 × 8 = <strong>12 m</strong>.'],
[['A vector has perpendicular components 5 m and 12 m. Find its magnitude.','Vektor memiliki komponen saling tegak lurus 5 m dan 12 m. Tentukan besarnya.'],13,'m','√(5² + 12²) = <strong>13 m</strong>.'],
[['A ball is launched horizontally at 6 m/s from a height of 5 m. Find range, using g = 10 m/s² and no air resistance.','Bola diluncurkan horizontal 6 m/s dari ketinggian 5 m. Tentukan jangkauan, dengan g = 10 m/s² tanpa hambatan udara.'],6,'m','5 = ½(10)t² → t = 1 s. x = 6 × 1 = <strong>6 m</strong>.'],
[['Move at 4 m/s on a circle of radius 2 m. Find centripetal acceleration.','Bergerak 4 m/s pada lingkaran berjari-jari 2 m. Tentukan percepatan sentripetal.'],8,'m/s²','a_c = 4²/2 = <strong>8 m/s²</strong>.'],
[['Convert 54 km/h to m/s.','Ubah 54 km/jam menjadi m/s.'],15,'m/s','54/3.6 = <strong>15 m/s</strong>.'],
[['Drop a ball from rest through 45 m. Find fall time with g = 10 m/s² and no air resistance.','Lepaskan bola dari diam hingga jatuh 45 m. Tentukan waktu jatuh dengan g = 10 m/s² tanpa hambatan udara.'],3,'s','45 = ½(10)t² → t = <strong>3 s</strong>.']
];
const advancedChallenge=[
[['Travel 100 m at 5 m/s then 100 m at 10 m/s. Find the whole-trip average speed to two decimal places.','Menempuh 100 m dengan 5 m/s lalu 100 m dengan 10 m/s. Tentukan kelajuan rata-rata seluruh perjalanan hingga dua desimal.'],6.67,'m/s','t = 20 + 10 = 30 s. 200/30 ≈ <strong>6.67 m/s</strong>.'],
[['Start at x = 0 with u = +6 m/s and a = −2 m/s² for 5 s. Find total distance.','Mulai dari x = 0 dengan u = +6 m/s dan a = −2 m/s² selama 5 s. Tentukan jarak total.'],13,'m','v = 0 at t = 3 s; x = 9 m. At 5 s, x = 5 m. Distance = 9 + 4 = <strong>13 m</strong>.'],
[['The signed areas under a velocity–time graph are +12 m and −5 m. Find displacement.','Luas bertanda di bawah grafik kecepatan–waktu adalah +12 m dan −5 m. Tentukan perpindahan.'],7,'m','12 − 5 = <strong>7 m</strong>.'],
[['Dimensionless vectors A = (2, 3) and B = (4, −1): find A · B.','Vektor tak berdimensi A = (2, 3) dan B = (4, −1): tentukan A · B.'],5,'1','2 × 4 + 3 × (−1) = <strong>5</strong>.'],
[['Launch at 10 m/s and 30°, landing at the same height. Find flight time with g = 10 m/s² and no air resistance.','Luncurkan dengan 10 m/s pada 30°, mendarat setinggi titik awal. Tentukan waktu terbang dengan g = 10 m/s² tanpa hambatan udara.'],1,'s','T = 2 × 10 × sin 30° / 10 = <strong>1 s</strong>.'],
[['A 0.5 kg object moves in a circle of radius 2 m at 4 m/s. Find the required inward force.','Benda 0.5 kg bergerak melingkar berjari-jari 2 m dengan 4 m/s. Tentukan gaya ke pusat yang diperlukan.'],4,'N','F_c = 0.5 × 4² / 2 = <strong>4 N</strong>.'],
[['A 2 kg object falls with linear drag coefficient b = 1 kg/s. Find terminal velocity using g = 10 m/s² and neglecting buoyancy.','Benda 2 kg jatuh dengan koefisien hambatan linear b = 1 kg/s. Tentukan kecepatan terminal dengan g = 10 m/s² dan abaikan gaya apung.'],20,'m/s','vₜ = mg/b = 2 × 10/1 = <strong>20 m/s</strong>.'],
[['At the highest point of a projectile with nonzero horizontal velocity, are velocity and acceleration both zero? Explain.','Di titik tertinggi peluru yang memiliki kecepatan horizontal tidak nol, apakah kecepatan dan percepatan keduanya nol? Jelaskan.'],null,'',['No. Only the vertical velocity is zero. Horizontal velocity remains nonzero, and acceleration remains downward at g.','Tidak. Hanya kecepatan vertikal yang nol. Kecepatan horizontal tetap tidak nol, dan percepatan tetap ke bawah sebesar g.']]
];
const easyKinChallenge=kinPages[10];kinPages[10]=()=>{if(kinState.level==='easy')return easyKinChallenge();const list=kinState.level==='medium'?mediumChallenge:advancedChallenge;return `<h2>${KT('Module challenge','Tantangan modul')}</h2><p class="intro">${KT('These questions belong to the selected level. Answers stay hidden until you open them.','Soal-soal ini khusus untuk tingkat yang dipilih. Jawaban tetap tersembunyi sampai kamu membukanya.')}</p><section class="activity">${list.map((q,i)=>kinTask('level-'+kinState.level+'-challenge-'+i,(i+1)+'. '+KT(...q[0]),q[1],q[2],Array.isArray(q[3])?KT(...q[3]):q[3])).join('')}</section>`};
kinPages.forEach((page,section)=>{kinPages[section]=()=>{const rank={easy:0,medium:1,advanced:2}[kinState.level],name=KT(...[['Easy · Understand','Mudah · Pahami'],['Medium · Apply','Menengah · Terapkan'],['Advanced · Reason · optional','Lanjutan · Bernalar · opsional']][rank]);return `<div class="kin-level-focus ${kinState.level}" role="status"><strong>${name}</strong><p>${KT(...kinGoals[section][rank])}</p><span>${KT(...[['Short questions with direct relationships.','Soal singkat dengan hubungan langsung.'],['Select a method, convert units, or combine two steps.','Pilih cara, konversikan satuan, atau gabungkan dua langkah.'],['Work through signs, assumptions and multiple stages.','Uraikan tanda, asumsi, dan beberapa tahap penyelesaian.']][rank])}</span></div>`+page().replace(/<section class="activity">\s*<\/section>/g,'')+kinSpecificTasks(section)}});
renderKin();
