'use strict';let examLang='id';const examChoices={},examChecked={},examOpen=new Set();const ET=(a,b)=>examLang==='id'?a:b,EP=p=>p[examLang==='id'?0:1],ee=id=>document.getElementById(id);
function examFeedback(i){return examChecked[i]===undefined?'':examChecked[i]?ET('Benar. Buka pembahasan untuk melihat alasannya.','Correct. Open the solution to see why.'):ET('Belum tepat. Coba lagi atau buka pembahasan.','Not quite. Try again or open the solution.')}
function examScore(){const checked=Object.keys(examChecked).length,right=Object.values(examChecked).filter(Boolean).length;ee('exam-score').textContent=ET('Terjawab: ','Answered: ')+Object.keys(examChoices).length+'/'+UNIT_EXAM.length+' · '+ET('Diperiksa: ','Checked: ')+checked+'/'+UNIT_EXAM.length+' · '+ET('Benar pada pilihan terakhir yang diperiksa: ','Correct in the latest checked selections: ')+right+'/'+UNIT_EXAM.length+(checked===UNIT_EXAM.length?' · '+ET('Nilai latihan: ','Practice score: ')+Math.round(right/UNIT_EXAM.length*100)+'/100':'')}
function checkExam(i){if(examChoices[i]===undefined){ee('exam-feedback-'+i).textContent=ET('Pilih satu jawaban terlebih dahulu.','Select an answer first.');return}examChecked[i]=examChoices[i]===UNIT_EXAM[i].answer;ee('exam-feedback-'+i).textContent=examFeedback(i);examScore()}
function renderExam(){document.documentElement.lang=examLang;ee('exam-language').value=examLang;ee('exam-title').textContent=ET('Bab 1 · Besaran fisika dan satuan','Chapter 1 · Physical quantities and units');document.title='PHY-LAB EDU | '+ee('exam-title').textContent;ee('exam-intro').textContent=ET('28 soal pilihan ganda untuk persiapan ujian. Pilih satu jawaban dari pilihan yang tersedia. Saran waktu: 60 menit. Soal 1–20: besaran, satuan dan dimensi; 21–22: massa jenis dan ketidakpastian (adaptasi Contoh 6.7); 23–25: konversi termometer; 26–27: awalan satuan dan massa jenis; 28: pengukuran berulang. Jawaban tersimpan selama halaman ini terbuka.','28 multiple-choice questions for exam preparation. Select one of the available options. Suggested time: 60 minutes. Questions 1–20: quantities, units and dimensions; 21–22: density and uncertainty (adapted from Example 6.7); 23–25: thermometer conversions; 26–27: prefixes and density; 28: repeated measurements. Answers last while this page stays open.');ee('exam-questions').innerHTML=UNIT_EXAM.map((q,i)=>`<section class="exam-question"><fieldset><legend>${i+1}. ${EP(q.prompt)}</legend>${q.promptMath?`<div class="math-line question-formula">${q.promptMath}</div>`:''}${q.diagram?thermometerDiagram(q.diagram):''}<div class="exam-options">${q.options.map((o,j)=>`<label><input type="radio" name="exam-${i}" data-question="${i}" value="${j}" ${examChoices[i]===j?'checked':''}><span>${'ABCDE'[j]}. ${EP(o)}</span></label>`).join('')}</div></fieldset><button data-exam-check="${i}">${ET('Periksa jawaban','Check answer')}</button><p id="exam-feedback-${i}" aria-live="polite">${examFeedback(i)}</p><details data-exam-open="${i}" ${examOpen.has(i)?'open':''}><summary>${ET('Tampilkan / sembunyikan pembahasan','Show / hide solution')}</summary>${renderWorkedSolution(q)}</details></section>`).join('');document.querySelectorAll('[data-question]').forEach(r=>r.onchange=()=>{const i=Number(r.dataset.question);examChoices[i]=Number(r.value);delete examChecked[i];ee('exam-feedback-'+i).textContent='';examScore()});document.querySelectorAll('[data-exam-check]').forEach(b=>b.onclick=()=>checkExam(Number(b.dataset.examCheck)));document.querySelectorAll('[data-exam-open]').forEach(d=>d.ontoggle=()=>{const i=Number(d.dataset.examOpen);d.open?examOpen.add(i):examOpen.delete(i)});ee('check-all').textContent=ET('Periksa semua jawaban','Check all answers');ee('check-all').onclick=()=>UNIT_EXAM.forEach((q,i)=>checkExam(i));examScore()}
ee('exam-language').onchange=e=>{examLang=e.target.value;renderExam()};renderExam();

function thermometerDiagram(d){
 const y=260-180*d.fraction;
 const svg=d.scales.map((a,i)=>{const x=100+i*240;return `<g><text x="${x}" y="32" text-anchor="middle" font-weight="700">${a[0]}</text><rect x="${x-10}" y="60" width="20" height="220" rx="10" fill="white" stroke="#123938" stroke-width="2"/><rect x="${x-5}" y="${y}" width="10" height="${280-y}" fill="#22868d"/><circle cx="${x}" cy="285" r="16" fill="#22868d" stroke="#123938" stroke-width="2"/>${[[80,a[2]],[260,a[1]],[y,a[3]]].map(([v,label])=>`<path d="M${x-18} ${v}h36" stroke="#123938"/><text x="${x+26}" y="${v+6}">${label}</text>`).join('')}</g>`}).join('');
 return `<figure class="thermometer-figure"><svg viewBox="0 0 500 330" role="img" aria-label="${ET('Diagram dua skala termometer linear dengan titik batas bawah dan atas','Two linear thermometer scales with lower and upper fixed points')}"><path d="M60 80H420M60 260H420" stroke="#819b9e" stroke-dasharray="5 5"/><path d="M60 ${y}H420" stroke="#22868d" stroke-dasharray="3 5"/>${svg}</svg><figcaption>${ET('Titik bawah: es mencair. Titik atas: air mendidih pada tekanan 1 atm. Skala dianggap linear; garis putus-putus menghubungkan suhu yang sama.','Lower fixed point: melting ice. Upper fixed point: boiling water at 1 atm. Scales are assumed linear; dashed lines connect equal temperatures.')}</figcaption></figure>`
}

function renderWorkedSolution(q){
 const steps=EP(q.solutionSteps)||[EP(q.explanation)];
 return `<div class="worked-solution"><h4>${ET('Pembahasan langkah demi langkah','Step-by-step solution')}</h4><ol class="solution-steps">${q.richSteps?q.richSteps.map(s=>`<li><p>${EP(s.text)}</p>${s.math?`<div class="math-line">${s.math}</div>`:''}</li>`).join(''):steps.map(s=>`<li><p>${s}</p></li>`).join('')}</ol>${q.solutionMath.length?`<div class="solution-calculation"><h4>${ET('Perhitungan','Calculation')}</h4>${q.solutionMath.map(m=>`<div class="math-line">${m}</div>`).join('')}</div>`:''}${q.solutionNote?`<p class="solution-note">${EP(q.solutionNote)}</p>`:''}<div class="solution-final"><span>${ET('Jawaban akhir','Final answer')}</span><strong>${'ABCDE'[q.answer]} · ${EP(q.options[q.answer])}</strong></div></div>`;
}
